BT2_DIR = nvbio

.PHONY: clean all

all:
	(cd "../build" && cmake -G "Visual Studio 17 2022" "../src/"$(BT2_DIR) && cmake --build . --parallel 16 --config Release)
	cd "../build" && cp nvBWT/Release/nvBWT.exe ../inst
	cd "../build" && cp nvBowtie/Release/nvBowtie.exe ../inst

clean:
	(cd "../build")
	rm -f nvBWT.exe
	rm -f nvBowtie.exe
	rm ../inst/nvBWT.exe
	rm ../inst/nvBowtie.exe 
